### ISSUE TITLE
argminmax backwards comptabile with rust 1.65.0 stable

### ISSUE THREAD

**Issue by sorhawell** [jvdd/argminmax#55]
Dear jvdd, thank you for your speedy algorithms :)

I maintain [r-polars](https://github.com/pola-rs/r-polars/) a sideshow to bigbrother py-polars/rust-polars [who adopted your crate around mid April.](https://github.com/pola-rs/polars/pull/8074)
The official R package repositories and build systems CRAN and R-Universe only supports rustc 1.58 and 1.65 respectively.

It seems you already made some effort to make argminmax backward compatible with rustc 1.66.0 stable, however not 1.65.0 stable.

[Therefore I cannot distribute r-polars currently on the R-universe repository](https://github.com/pola-rs/r-polars/issues/208)

Would it be possible to also become backwards compatible with 1.65.0 stable(R-universe build) or even 1.62.0 stable (previous polars minimal supported version)?

best

**Comment by jvdd** [comment]
Oh wow, scrap that - removing the unnecessary repetition operator (i.e., `*`) seems to resolve the issue :upside_down_face:

**Comment by sorhawell** [comment]
Hi jvdd. Thank you for looking into this so fast ! :)
 I can try to compile polars with a argminmax branch without this * operator tonight or Friday.

**Comment by sorhawell** [comment]
Is it the operator on L758 or L779 or both?

**Comment by jvdd** [comment]
This solved it for me!

```rs
#[cfg(any(
    target_arch = "x86",
    target_arch = "x86_64",
    all(target_arch = "aarch64", feature = "float"), // is stable for f64
    feature = "nightly_simd"
))]
macro_rules! impl_SIMDArgMinMax {
    ($scalar_dtype:ty, $simd_vec_dtype:ty, $simd_mask_dtype:ty, $lane_size:expr, $scalar_struct:ty, $simd_struct:ty, $target:expr) => {
        impl SIMDArgMinMax<$scalar_dtype, $simd_vec_dtype, $simd_mask_dtype, $lane_size, $scalar_struct> for $simd_struct {
            #[target_feature(enable = $target)]
            unsafe fn argminmax(data: &[$scalar_dtype]) -> (usize, usize) {
                Self::_argminmax(data)
            }

            #[target_feature(enable = $target)]
            unsafe fn argmin(data: &[$scalar_dtype]) -> usize {
                Self::_argmin(data)
                // TODO: test if this is same speed as _argmin
                // Self::_argminmax(data).0
            }

            #[target_feature(enable = $target)]
            unsafe fn argmax(data: &[$scalar_dtype]) -> usize {
                Self::_argmax(data)
                // Self::_argminmax(data).1
            }
        }
    }
}
```

**Comment by jvdd** [comment]
Okay - very weird stuff going on.
This "fix" does not work on my 2nd development server, and in CI-CD I can build without any problems on 1.62 #56 :upside_down_face:

**Comment by jvdd** [comment]
- `rustc 1.62` builds without errors
- `rustc 1.65` builds with errors...

**Comment by jvdd** [comment]
> Okay finally narrowing this down - it seems to be a rustc 1.65 specific issue..
> 
> * `rustc 1.62` builds heavy_check_mark
> * `rustc 1.63` builds heavy_check_mark
> * `rustc 1.64` builds heavy_check_mark
> * `rustc 1.65` compilation error x
> * `rustc 1.66` builds heavy_check_mark

My apologies for the messy comments :upside_down_face: 

After further investigation I am quite confident that this is an internal compiler error that is only present in  `rustc 1.65` ...

Any pointers on how I can elegantly avoid this error is welcome :upside_down_face:

**Comment by sorhawell** [comment]
Was  the * operator an issue in the end?

**Comment by sorhawell** [comment]
I found a quick-fix 

When 1.65.0 is required, I can compile with arminmax 0.6.1 as dependency when adding below to r-polars Cargo.toml
```toml
[profile.release.package.argminmax]
opt-level = 1
```

**Comment by sorhawell** [comment]
We cross our fingers debian do not settle on rust 1.65, and otherwise we will run with `opt-level = 1` on that release channel.

I filed an ICE report for good measures: https://github.com/rust-lang/rust/issues/111498


many thanks @jvdd ! from my view point this resolution is pretty alright and we can close the issue :)

**Comment by jvdd** [comment]
Thanks for further delving into this issue and creating the ICW report @sorhawell 

:crossed_fingers: for debian to not settle on rust 1.65 :smiling_face_with_tear:
